/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using HookSniff.Api;
using HookSniff.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace HookSniff.Test.Api
{
    /// <summary>
    ///  Class for testing BillingApi
    /// </summary>
    public sealed class BillingApiTests : ApiTestsBase
    {
        private readonly IBillingApi _instance;

        public BillingApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IBillingApi>();
        }

        /// <summary>
        /// Test BillingInvoicesGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task BillingInvoicesGetAsyncTest()
        {
            var response = await _instance.BillingInvoicesGetAsync();
            var model = response.Ok();
            Assert.IsType<List<InvoiceResponse>>(model);
        }

        /// <summary>
        /// Test BillingPortalPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task BillingPortalPostAsyncTest()
        {
            var response = await _instance.BillingPortalPostAsync();
            var model = response.Ok();
            Assert.IsType<BillingPortalPost200Response>(model);
        }

        /// <summary>
        /// Test BillingSubscriptionGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task BillingSubscriptionGetAsyncTest()
        {
            var response = await _instance.BillingSubscriptionGetAsync();
            var model = response.Ok();
            Assert.IsType<SubscriptionResponse>(model);
        }

        /// <summary>
        /// Test BillingUpgradePost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task BillingUpgradePostAsyncTest()
        {
            UpgradeRequest upgradeRequest = default!;
            var response = await _instance.BillingUpgradePostAsync(upgradeRequest);
            var model = response.Ok();
            Assert.IsType<UpgradeResponse>(model);
        }

        /// <summary>
        /// Test BillingUsageGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task BillingUsageGetAsyncTest()
        {
            var response = await _instance.BillingUsageGetAsync();
            var model = response.Ok();
            Assert.IsType<UsageResponse>(model);
        }

        /// <summary>
        /// Test BillingWebhookIyzicoPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task BillingWebhookIyzicoPostAsyncTest()
        {
            Object body = default!;
            await _instance.BillingWebhookIyzicoPostAsync(body);
        }

        /// <summary>
        /// Test BillingWebhookPolarPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task BillingWebhookPolarPostAsyncTest()
        {
            Object body = default!;
            await _instance.BillingWebhookPolarPostAsync(body);
        }

        /// <summary>
        /// Test BillingWebhookPost
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task BillingWebhookPostAsyncTest()
        {
            Object body = default!;
            await _instance.BillingWebhookPostAsync(body);
        }
    }
}
