/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HookSniff.Model;
using HookSniff.Client;
using System.Reflection;

namespace HookSniff.Test.Model
{
    /// <summary>
    ///  Class for testing BatchResponseErrorsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchResponseErrorsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchResponseErrorsInner
        //private BatchResponseErrorsInner instance;

        public BatchResponseErrorsInnerTests()
        {
            // TODO uncomment below to create an instance of BatchResponseErrorsInner
            //instance = new BatchResponseErrorsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchResponseErrorsInner
        /// </summary>
        [Fact]
        public void BatchResponseErrorsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchResponseErrorsInner
            //Assert.IsType<BatchResponseErrorsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
