/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HookSniff.Model;
using HookSniff.Client;
using System.Reflection;

namespace HookSniff.Test.Model
{
    /// <summary>
    ///  Class for testing CancelSubscriptionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CancelSubscriptionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CancelSubscriptionRequest
        //private CancelSubscriptionRequest instance;

        public CancelSubscriptionRequestTests()
        {
            // TODO uncomment below to create an instance of CancelSubscriptionRequest
            //instance = new CancelSubscriptionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CancelSubscriptionRequest
        /// </summary>
        [Fact]
        public void CancelSubscriptionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CancelSubscriptionRequest
            //Assert.IsType<CancelSubscriptionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
    }
}
