/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HookSniff.Model;
using HookSniff.Client;
using System.Reflection;

namespace HookSniff.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerResponse
        //private CustomerResponse instance;

        public CustomerResponseTests()
        {
            // TODO uncomment below to create an instance of CustomerResponse
            //instance = new CustomerResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerResponse
        /// </summary>
        [Fact]
        public void CustomerResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerResponse
            //Assert.IsType<CustomerResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Plan'
        /// </summary>
        [Fact]
        public void PlanTest()
        {
            // TODO unit test for the property 'Plan'
        }

        /// <summary>
        /// Test the property 'WebhookLimit'
        /// </summary>
        [Fact]
        public void WebhookLimitTest()
        {
            // TODO unit test for the property 'WebhookLimit'
        }

        /// <summary>
        /// Test the property 'WebhookCount'
        /// </summary>
        [Fact]
        public void WebhookCountTest()
        {
            // TODO unit test for the property 'WebhookCount'
        }

        /// <summary>
        /// Test the property 'IsAdmin'
        /// </summary>
        [Fact]
        public void IsAdminTest()
        {
            // TODO unit test for the property 'IsAdmin'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ApiKey'
        /// </summary>
        [Fact]
        public void ApiKeyTest()
        {
            // TODO unit test for the property 'ApiKey'
        }
    }
}
