/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HookSniff.Model;
using HookSniff.Client;
using System.Reflection;

namespace HookSniff.Test.Model
{
    /// <summary>
    ///  Class for testing Delivery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeliveryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Delivery
        //private Delivery instance;

        public DeliveryTests()
        {
            // TODO uncomment below to create an instance of Delivery
            //instance = new Delivery();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Delivery
        /// </summary>
        [Fact]
        public void DeliveryInstanceTest()
        {
            // TODO uncomment below to test "IsType" Delivery
            //Assert.IsType<Delivery>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'EndpointId'
        /// </summary>
        [Fact]
        public void EndpointIdTest()
        {
            // TODO unit test for the property 'EndpointId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'AttemptCount'
        /// </summary>
        [Fact]
        public void AttemptCountTest()
        {
            // TODO unit test for the property 'AttemptCount'
        }

        /// <summary>
        /// Test the property 'ReplayCount'
        /// </summary>
        [Fact]
        public void ReplayCountTest()
        {
            // TODO unit test for the property 'ReplayCount'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }

        /// <summary>
        /// Test the property 'ResponseStatus'
        /// </summary>
        [Fact]
        public void ResponseStatusTest()
        {
            // TODO unit test for the property 'ResponseStatus'
        }
    }
}
