/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HookSniff.Model;
using HookSniff.Client;
using System.Reflection;

namespace HookSniff.Test.Model
{
    /// <summary>
    ///  Class for testing ExportDataResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExportDataResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExportDataResponse
        //private ExportDataResponse instance;

        public ExportDataResponseTests()
        {
            // TODO uncomment below to create an instance of ExportDataResponse
            //instance = new ExportDataResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExportDataResponse
        /// </summary>
        [Fact]
        public void ExportDataResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExportDataResponse
            //Assert.IsType<ExportDataResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ExportedAt'
        /// </summary>
        [Fact]
        public void ExportedAtTest()
        {
            // TODO unit test for the property 'ExportedAt'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'Endpoints'
        /// </summary>
        [Fact]
        public void EndpointsTest()
        {
            // TODO unit test for the property 'Endpoints'
        }

        /// <summary>
        /// Test the property 'Deliveries'
        /// </summary>
        [Fact]
        public void DeliveriesTest()
        {
            // TODO unit test for the property 'Deliveries'
        }

        /// <summary>
        /// Test the property 'Teams'
        /// </summary>
        [Fact]
        public void TeamsTest()
        {
            // TODO unit test for the property 'Teams'
        }
    }
}
