/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HookSniff.Model;
using HookSniff.Client;
using System.Reflection;

namespace HookSniff.Test.Model
{
    /// <summary>
    ///  Class for testing NotificationsUnreadCountGet200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotificationsUnreadCountGet200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NotificationsUnreadCountGet200Response
        //private NotificationsUnreadCountGet200Response instance;

        public NotificationsUnreadCountGet200ResponseTests()
        {
            // TODO uncomment below to create an instance of NotificationsUnreadCountGet200Response
            //instance = new NotificationsUnreadCountGet200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotificationsUnreadCountGet200Response
        /// </summary>
        [Fact]
        public void NotificationsUnreadCountGet200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" NotificationsUnreadCountGet200Response
            //Assert.IsType<NotificationsUnreadCountGet200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
    }
}
