/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HookSniff.Model;
using HookSniff.Client;
using System.Reflection;

namespace HookSniff.Test.Model
{
    /// <summary>
    ///  Class for testing TeamMemberListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamMemberListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamMemberListResponse
        //private TeamMemberListResponse instance;

        public TeamMemberListResponseTests()
        {
            // TODO uncomment below to create an instance of TeamMemberListResponse
            //instance = new TeamMemberListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamMemberListResponse
        /// </summary>
        [Fact]
        public void TeamMemberListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TeamMemberListResponse
            //Assert.IsType<TeamMemberListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
