// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HookSniff.Client;

namespace HookSniff.Model
{
    /// <summary>
    /// BatchReplayRequest
    /// </summary>
    public partial class BatchReplayRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchReplayRequest" /> class.
        /// </summary>
        /// <param name="ids">ids</param>
        [JsonConstructor]
        public BatchReplayRequest(List<Guid> ids)
        {
            Ids = ids;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Ids
        /// </summary>
        [JsonPropertyName("ids")]
        public List<Guid> Ids { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchReplayRequest {\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="BatchReplayRequest" />
    /// </summary>
    public class BatchReplayRequestJsonConverter : JsonConverter<BatchReplayRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="BatchReplayRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override BatchReplayRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<Guid>?> ids = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ids":
                            ids = new Option<List<Guid>?>(JsonSerializer.Deserialize<List<Guid>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!ids.IsSet)
                throw new ArgumentException("Property is required for class BatchReplayRequest.", nameof(ids));

            if (ids.IsSet && ids.Value == null)
                throw new ArgumentNullException(nameof(ids), "Property is not nullable for class BatchReplayRequest.");

            return new BatchReplayRequest(ids.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="BatchReplayRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="batchReplayRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, BatchReplayRequest batchReplayRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, batchReplayRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="BatchReplayRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="batchReplayRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, BatchReplayRequest batchReplayRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (batchReplayRequest.Ids == null)
                throw new ArgumentNullException(nameof(batchReplayRequest.Ids), "Property is required for class BatchReplayRequest.");

            writer.WritePropertyName("ids");
            JsonSerializer.Serialize(writer, batchReplayRequest.Ids, jsonSerializerOptions);
        }
    }
}
