// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HookSniff.Client;

namespace HookSniff.Model
{
    /// <summary>
    /// CreateEndpointRequest
    /// </summary>
    public partial class CreateEndpointRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateEndpointRequest" /> class.
        /// </summary>
        /// <param name="url">url</param>
        /// <param name="description">description</param>
        /// <param name="allowedIps">allowedIps</param>
        /// <param name="eventFilter">eventFilter</param>
        /// <param name="customHeaders">customHeaders</param>
        /// <param name="retryPolicy">retryPolicy</param>
        /// <param name="routingStrategy">routingStrategy</param>
        /// <param name="fallbackUrl">fallbackUrl</param>
        /// <param name="format">format (default to FormatEnum.Standard)</param>
        [JsonConstructor]
        public CreateEndpointRequest(string url, Option<string?> description = default, Option<List<string>?> allowedIps = default, Option<List<string>?> eventFilter = default, Option<Object?> customHeaders = default, Option<RetryPolicy?> retryPolicy = default, Option<RoutingStrategyEnum?> routingStrategy = default, Option<string?> fallbackUrl = default, Option<FormatEnum?> format = default)
        {
            Url = url;
            DescriptionOption = description;
            AllowedIpsOption = allowedIps;
            EventFilterOption = eventFilter;
            CustomHeadersOption = customHeaders;
            RetryPolicyOption = retryPolicy;
            RoutingStrategyOption = routingStrategy;
            FallbackUrlOption = fallbackUrl;
            FormatOption = format;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines RoutingStrategy
        /// </summary>
        public enum RoutingStrategyEnum
        {
            /// <summary>
            /// Enum RoundRobin for value: round-robin
            /// </summary>
            RoundRobin = 1,

            /// <summary>
            /// Enum Latency for value: latency
            /// </summary>
            Latency = 2,

            /// <summary>
            /// Enum Failover for value: failover
            /// </summary>
            Failover = 3
        }

        /// <summary>
        /// Returns a <see cref="RoutingStrategyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static RoutingStrategyEnum RoutingStrategyEnumFromString(string value)
        {
            if (value.Equals("round-robin"))
                return RoutingStrategyEnum.RoundRobin;

            if (value.Equals("latency"))
                return RoutingStrategyEnum.Latency;

            if (value.Equals("failover"))
                return RoutingStrategyEnum.Failover;

            throw new NotImplementedException($"Could not convert value to type RoutingStrategyEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="RoutingStrategyEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static RoutingStrategyEnum? RoutingStrategyEnumFromStringOrDefault(string value)
        {
            if (value.Equals("round-robin"))
                return RoutingStrategyEnum.RoundRobin;

            if (value.Equals("latency"))
                return RoutingStrategyEnum.Latency;

            if (value.Equals("failover"))
                return RoutingStrategyEnum.Failover;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="RoutingStrategyEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string RoutingStrategyEnumToJsonValue(RoutingStrategyEnum? value)
        {
            if (value == RoutingStrategyEnum.RoundRobin)
                return "round-robin";

            if (value == RoutingStrategyEnum.Latency)
                return "latency";

            if (value == RoutingStrategyEnum.Failover)
                return "failover";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of RoutingStrategy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RoutingStrategyEnum?> RoutingStrategyOption { get; private set; }

        /// <summary>
        /// Gets or Sets RoutingStrategy
        /// </summary>
        [JsonPropertyName("routing_strategy")]
        public RoutingStrategyEnum? RoutingStrategy { get { return this.RoutingStrategyOption.Value; } set { this.RoutingStrategyOption = new(value); } }

        /// <summary>
        /// Defines Format
        /// </summary>
        public enum FormatEnum
        {
            /// <summary>
            /// Enum Standard for value: standard
            /// </summary>
            Standard = 1,

            /// <summary>
            /// Enum Cloudevents for value: cloudevents
            /// </summary>
            Cloudevents = 2
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FormatEnum FormatEnumFromString(string value)
        {
            if (value.Equals("standard"))
                return FormatEnum.Standard;

            if (value.Equals("cloudevents"))
                return FormatEnum.Cloudevents;

            throw new NotImplementedException($"Could not convert value to type FormatEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FormatEnum? FormatEnumFromStringOrDefault(string value)
        {
            if (value.Equals("standard"))
                return FormatEnum.Standard;

            if (value.Equals("cloudevents"))
                return FormatEnum.Cloudevents;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FormatEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FormatEnumToJsonValue(FormatEnum? value)
        {
            if (value == FormatEnum.Standard)
                return "standard";

            if (value == FormatEnum.Cloudevents)
                return "cloudevents";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Format
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FormatEnum?> FormatOption { get; private set; }

        /// <summary>
        /// Gets or Sets Format
        /// </summary>
        [JsonPropertyName("format")]
        public FormatEnum? Format { get { return this.FormatOption.Value; } set { this.FormatOption = new(value); } }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of AllowedIps
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> AllowedIpsOption { get; private set; }

        /// <summary>
        /// Gets or Sets AllowedIps
        /// </summary>
        [JsonPropertyName("allowed_ips")]
        public List<string>? AllowedIps { get { return this.AllowedIpsOption.Value; } set { this.AllowedIpsOption = new(value); } }

        /// <summary>
        /// Used to track the state of EventFilter
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> EventFilterOption { get; private set; }

        /// <summary>
        /// Gets or Sets EventFilter
        /// </summary>
        [JsonPropertyName("event_filter")]
        public List<string>? EventFilter { get { return this.EventFilterOption.Value; } set { this.EventFilterOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomHeaders
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> CustomHeadersOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomHeaders
        /// </summary>
        [JsonPropertyName("custom_headers")]
        public Object? CustomHeaders { get { return this.CustomHeadersOption.Value; } set { this.CustomHeadersOption = new(value); } }

        /// <summary>
        /// Used to track the state of RetryPolicy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<RetryPolicy?> RetryPolicyOption { get; private set; }

        /// <summary>
        /// Gets or Sets RetryPolicy
        /// </summary>
        [JsonPropertyName("retry_policy")]
        public RetryPolicy? RetryPolicy { get { return this.RetryPolicyOption.Value; } set { this.RetryPolicyOption = new(value); } }

        /// <summary>
        /// Used to track the state of FallbackUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FallbackUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets FallbackUrl
        /// </summary>
        [JsonPropertyName("fallback_url")]
        public string? FallbackUrl { get { return this.FallbackUrlOption.Value; } set { this.FallbackUrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateEndpointRequest {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  AllowedIps: ").Append(AllowedIps).Append("\n");
            sb.Append("  EventFilter: ").Append(EventFilter).Append("\n");
            sb.Append("  CustomHeaders: ").Append(CustomHeaders).Append("\n");
            sb.Append("  RetryPolicy: ").Append(RetryPolicy).Append("\n");
            sb.Append("  RoutingStrategy: ").Append(RoutingStrategy).Append("\n");
            sb.Append("  FallbackUrl: ").Append(FallbackUrl).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateEndpointRequest" />
    /// </summary>
    public class CreateEndpointRequestJsonConverter : JsonConverter<CreateEndpointRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateEndpointRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateEndpointRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<string?> description = default;
            Option<List<string>?> allowedIps = default;
            Option<List<string>?> eventFilter = default;
            Option<Object?> customHeaders = default;
            Option<RetryPolicy?> retryPolicy = default;
            Option<CreateEndpointRequest.RoutingStrategyEnum?> routingStrategy = default;
            Option<string?> fallbackUrl = default;
            Option<CreateEndpointRequest.FormatEnum?> format = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "allowed_ips":
                            allowedIps = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "event_filter":
                            eventFilter = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "custom_headers":
                            customHeaders = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "retry_policy":
                            retryPolicy = new Option<RetryPolicy?>(JsonSerializer.Deserialize<RetryPolicy>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "routing_strategy":
                            string? routingStrategyRawValue = utf8JsonReader.GetString();
                            if (routingStrategyRawValue != null)
                                routingStrategy = new Option<CreateEndpointRequest.RoutingStrategyEnum?>(CreateEndpointRequest.RoutingStrategyEnumFromStringOrDefault(routingStrategyRawValue));
                            break;
                        case "fallback_url":
                            fallbackUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "format":
                            string? formatRawValue = utf8JsonReader.GetString();
                            if (formatRawValue != null)
                                format = new Option<CreateEndpointRequest.FormatEnum?>(CreateEndpointRequest.FormatEnumFromStringOrDefault(formatRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class CreateEndpointRequest.", nameof(url));

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class CreateEndpointRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class CreateEndpointRequest.");

            if (allowedIps.IsSet && allowedIps.Value == null)
                throw new ArgumentNullException(nameof(allowedIps), "Property is not nullable for class CreateEndpointRequest.");

            if (eventFilter.IsSet && eventFilter.Value == null)
                throw new ArgumentNullException(nameof(eventFilter), "Property is not nullable for class CreateEndpointRequest.");

            if (customHeaders.IsSet && customHeaders.Value == null)
                throw new ArgumentNullException(nameof(customHeaders), "Property is not nullable for class CreateEndpointRequest.");

            if (retryPolicy.IsSet && retryPolicy.Value == null)
                throw new ArgumentNullException(nameof(retryPolicy), "Property is not nullable for class CreateEndpointRequest.");

            if (routingStrategy.IsSet && routingStrategy.Value == null)
                throw new ArgumentNullException(nameof(routingStrategy), "Property is not nullable for class CreateEndpointRequest.");

            if (fallbackUrl.IsSet && fallbackUrl.Value == null)
                throw new ArgumentNullException(nameof(fallbackUrl), "Property is not nullable for class CreateEndpointRequest.");

            if (format.IsSet && format.Value == null)
                throw new ArgumentNullException(nameof(format), "Property is not nullable for class CreateEndpointRequest.");

            return new CreateEndpointRequest(url.Value!, description, allowedIps, eventFilter, customHeaders, retryPolicy, routingStrategy, fallbackUrl, format);
        }

        /// <summary>
        /// Serializes a <see cref="CreateEndpointRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createEndpointRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateEndpointRequest createEndpointRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createEndpointRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateEndpointRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createEndpointRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateEndpointRequest createEndpointRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createEndpointRequest.Url == null)
                throw new ArgumentNullException(nameof(createEndpointRequest.Url), "Property is required for class CreateEndpointRequest.");

            if (createEndpointRequest.DescriptionOption.IsSet && createEndpointRequest.Description == null)
                throw new ArgumentNullException(nameof(createEndpointRequest.Description), "Property is required for class CreateEndpointRequest.");

            if (createEndpointRequest.AllowedIpsOption.IsSet && createEndpointRequest.AllowedIps == null)
                throw new ArgumentNullException(nameof(createEndpointRequest.AllowedIps), "Property is required for class CreateEndpointRequest.");

            if (createEndpointRequest.EventFilterOption.IsSet && createEndpointRequest.EventFilter == null)
                throw new ArgumentNullException(nameof(createEndpointRequest.EventFilter), "Property is required for class CreateEndpointRequest.");

            if (createEndpointRequest.CustomHeadersOption.IsSet && createEndpointRequest.CustomHeaders == null)
                throw new ArgumentNullException(nameof(createEndpointRequest.CustomHeaders), "Property is required for class CreateEndpointRequest.");

            if (createEndpointRequest.RetryPolicyOption.IsSet && createEndpointRequest.RetryPolicy == null)
                throw new ArgumentNullException(nameof(createEndpointRequest.RetryPolicy), "Property is required for class CreateEndpointRequest.");

            if (createEndpointRequest.FallbackUrlOption.IsSet && createEndpointRequest.FallbackUrl == null)
                throw new ArgumentNullException(nameof(createEndpointRequest.FallbackUrl), "Property is required for class CreateEndpointRequest.");

            writer.WriteString("url", createEndpointRequest.Url);

            if (createEndpointRequest.DescriptionOption.IsSet)
                writer.WriteString("description", createEndpointRequest.Description);

            if (createEndpointRequest.AllowedIpsOption.IsSet)
            {
                writer.WritePropertyName("allowed_ips");
                JsonSerializer.Serialize(writer, createEndpointRequest.AllowedIps, jsonSerializerOptions);
            }
            if (createEndpointRequest.EventFilterOption.IsSet)
            {
                writer.WritePropertyName("event_filter");
                JsonSerializer.Serialize(writer, createEndpointRequest.EventFilter, jsonSerializerOptions);
            }
            if (createEndpointRequest.CustomHeadersOption.IsSet)
            {
                writer.WritePropertyName("custom_headers");
                JsonSerializer.Serialize(writer, createEndpointRequest.CustomHeaders, jsonSerializerOptions);
            }
            if (createEndpointRequest.RetryPolicyOption.IsSet)
            {
                writer.WritePropertyName("retry_policy");
                JsonSerializer.Serialize(writer, createEndpointRequest.RetryPolicy, jsonSerializerOptions);
            }
            var routingStrategyRawValue = CreateEndpointRequest.RoutingStrategyEnumToJsonValue(createEndpointRequest.RoutingStrategyOption.Value!.Value);
            writer.WriteString("routing_strategy", routingStrategyRawValue);
            if (createEndpointRequest.FallbackUrlOption.IsSet)
                writer.WriteString("fallback_url", createEndpointRequest.FallbackUrl);

            var formatRawValue = CreateEndpointRequest.FormatEnumToJsonValue(createEndpointRequest.FormatOption.Value!.Value);
            writer.WriteString("format", formatRawValue);
        }
    }
}
