// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HookSniff.Client;

namespace HookSniff.Model
{
    /// <summary>
    /// Request to create a new alert rule
    /// </summary>
    public partial class CreateAlertRuleRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAlertRuleRequest" /> class.
        /// </summary>
        /// <param name="name">Human-readable alert name</param>
        /// <param name="condition">Condition that triggers the alert</param>
        /// <param name="threshold">Threshold value for the condition</param>
        /// <param name="channels">Notification channels to alert on</param>
        [JsonConstructor]
        public CreateAlertRuleRequest(string name, ConditionEnum condition, int threshold, List<CreateAlertRuleRequest.ChannelsEnum> channels)
        {
            Name = name;
            Condition = condition;
            Threshold = threshold;
            Channels = channels;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Condition that triggers the alert
        /// </summary>
        /// <value>Condition that triggers the alert</value>
        public enum ConditionEnum
        {
            /// <summary>
            /// Enum FailureRate for value: failure_rate
            /// </summary>
            FailureRate = 1,

            /// <summary>
            /// Enum Latency for value: latency
            /// </summary>
            Latency = 2,

            /// <summary>
            /// Enum ConsecutiveFailures for value: consecutive_failures
            /// </summary>
            ConsecutiveFailures = 3
        }

        /// <summary>
        /// Returns a <see cref="ConditionEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ConditionEnum ConditionEnumFromString(string value)
        {
            if (value.Equals("failure_rate"))
                return ConditionEnum.FailureRate;

            if (value.Equals("latency"))
                return ConditionEnum.Latency;

            if (value.Equals("consecutive_failures"))
                return ConditionEnum.ConsecutiveFailures;

            throw new NotImplementedException($"Could not convert value to type ConditionEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ConditionEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ConditionEnum? ConditionEnumFromStringOrDefault(string value)
        {
            if (value.Equals("failure_rate"))
                return ConditionEnum.FailureRate;

            if (value.Equals("latency"))
                return ConditionEnum.Latency;

            if (value.Equals("consecutive_failures"))
                return ConditionEnum.ConsecutiveFailures;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ConditionEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ConditionEnumToJsonValue(ConditionEnum value)
        {
            if (value == ConditionEnum.FailureRate)
                return "failure_rate";

            if (value == ConditionEnum.Latency)
                return "latency";

            if (value == ConditionEnum.ConsecutiveFailures)
                return "consecutive_failures";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Condition that triggers the alert
        /// </summary>
        /// <value>Condition that triggers the alert</value>
        [JsonPropertyName("condition")]
        public ConditionEnum Condition { get; set; }

        /// <summary>
        /// Defines Channels
        /// </summary>
        public enum ChannelsEnum
        {
            /// <summary>
            /// Enum Slack for value: slack
            /// </summary>
            Slack = 1,

            /// <summary>
            /// Enum Email for value: email
            /// </summary>
            Email = 2,

            /// <summary>
            /// Enum Webhook for value: webhook
            /// </summary>
            Webhook = 3
        }

        /// <summary>
        /// Returns a <see cref="ChannelsEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ChannelsEnum ChannelsEnumFromString(string value)
        {
            if (value.Equals("slack"))
                return ChannelsEnum.Slack;

            if (value.Equals("email"))
                return ChannelsEnum.Email;

            if (value.Equals("webhook"))
                return ChannelsEnum.Webhook;

            throw new NotImplementedException($"Could not convert value to type ChannelsEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ChannelsEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ChannelsEnum? ChannelsEnumFromStringOrDefault(string value)
        {
            if (value.Equals("slack"))
                return ChannelsEnum.Slack;

            if (value.Equals("email"))
                return ChannelsEnum.Email;

            if (value.Equals("webhook"))
                return ChannelsEnum.Webhook;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ChannelsEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ChannelsEnumToJsonValue(ChannelsEnum? value)
        {
            if (value == ChannelsEnum.Slack)
                return "slack";

            if (value == ChannelsEnum.Email)
                return "email";

            if (value == ChannelsEnum.Webhook)
                return "webhook";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Human-readable alert name
        /// </summary>
        /// <value>Human-readable alert name</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Threshold value for the condition
        /// </summary>
        /// <value>Threshold value for the condition</value>
        [JsonPropertyName("threshold")]
        public int Threshold { get; set; }

        /// <summary>
        /// Notification channels to alert on
        /// </summary>
        /// <value>Notification channels to alert on</value>
        [JsonPropertyName("channels")]
        public List<CreateAlertRuleRequest.ChannelsEnum> Channels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateAlertRuleRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  Threshold: ").Append(Threshold).Append("\n");
            sb.Append("  Channels: ").Append(Channels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateAlertRuleRequest" />
    /// </summary>
    public class CreateAlertRuleRequestJsonConverter : JsonConverter<CreateAlertRuleRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateAlertRuleRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateAlertRuleRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<CreateAlertRuleRequest.ConditionEnum?> condition = default;
            Option<int?> threshold = default;
            Option<List<CreateAlertRuleRequest.ChannelsEnum>?> channels = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "condition":
                            string? conditionRawValue = utf8JsonReader.GetString();
                            if (conditionRawValue != null)
                                condition = new Option<CreateAlertRuleRequest.ConditionEnum?>(CreateAlertRuleRequest.ConditionEnumFromStringOrDefault(conditionRawValue));
                            break;
                        case "threshold":
                            threshold = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "channels":
                            channels = new Option<List<CreateAlertRuleRequest.ChannelsEnum>?>(JsonSerializer.Deserialize<List<CreateAlertRuleRequest.ChannelsEnum>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CreateAlertRuleRequest.", nameof(name));

            if (!condition.IsSet)
                throw new ArgumentException("Property is required for class CreateAlertRuleRequest.", nameof(condition));

            if (!threshold.IsSet)
                throw new ArgumentException("Property is required for class CreateAlertRuleRequest.", nameof(threshold));

            if (!channels.IsSet)
                throw new ArgumentException("Property is required for class CreateAlertRuleRequest.", nameof(channels));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateAlertRuleRequest.");

            if (condition.IsSet && condition.Value == null)
                throw new ArgumentNullException(nameof(condition), "Property is not nullable for class CreateAlertRuleRequest.");

            if (threshold.IsSet && threshold.Value == null)
                throw new ArgumentNullException(nameof(threshold), "Property is not nullable for class CreateAlertRuleRequest.");

            if (channels.IsSet && channels.Value == null)
                throw new ArgumentNullException(nameof(channels), "Property is not nullable for class CreateAlertRuleRequest.");

            return new CreateAlertRuleRequest(name.Value!, condition.Value!.Value!, threshold.Value!.Value!, channels.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CreateAlertRuleRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createAlertRuleRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateAlertRuleRequest createAlertRuleRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createAlertRuleRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateAlertRuleRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createAlertRuleRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateAlertRuleRequest createAlertRuleRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createAlertRuleRequest.Name == null)
                throw new ArgumentNullException(nameof(createAlertRuleRequest.Name), "Property is required for class CreateAlertRuleRequest.");

            if (createAlertRuleRequest.Channels == null)
                throw new ArgumentNullException(nameof(createAlertRuleRequest.Channels), "Property is required for class CreateAlertRuleRequest.");

            writer.WriteString("name", createAlertRuleRequest.Name);

            var conditionRawValue = CreateAlertRuleRequest.ConditionEnumToJsonValue(createAlertRuleRequest.Condition);
            writer.WriteString("condition", conditionRawValue);
            writer.WriteNumber("threshold", createAlertRuleRequest.Threshold);

            writer.WritePropertyName("channels");
            JsonSerializer.Serialize(writer, createAlertRuleRequest.Channels, jsonSerializerOptions);
        }
    }
}
