// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HookSniff.Client;

namespace HookSniff.Model
{
    /// <summary>
    /// CreateApiKeyResponse
    /// </summary>
    public partial class CreateApiKeyResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateApiKeyResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="key">Full API key — only shown once</param>
        /// <param name="prefix">prefix</param>
        /// <param name="message">message</param>
        [JsonConstructor]
        public CreateApiKeyResponse(Guid id, string key, string prefix, string message)
        {
            Id = id;
            Key = key;
            Prefix = prefix;
            Message = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Full API key — only shown once
        /// </summary>
        /// <value>Full API key — only shown once</value>
        [JsonPropertyName("key")]
        public string Key { get; set; }

        /// <summary>
        /// Gets or Sets Prefix
        /// </summary>
        [JsonPropertyName("prefix")]
        public string Prefix { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateApiKeyResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Prefix: ").Append(Prefix).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateApiKeyResponse" />
    /// </summary>
    public class CreateApiKeyResponseJsonConverter : JsonConverter<CreateApiKeyResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateApiKeyResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateApiKeyResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> key = default;
            Option<string?> prefix = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "key":
                            key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "prefix":
                            prefix = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class CreateApiKeyResponse.", nameof(id));

            if (!key.IsSet)
                throw new ArgumentException("Property is required for class CreateApiKeyResponse.", nameof(key));

            if (!prefix.IsSet)
                throw new ArgumentException("Property is required for class CreateApiKeyResponse.", nameof(prefix));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class CreateApiKeyResponse.", nameof(message));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class CreateApiKeyResponse.");

            if (key.IsSet && key.Value == null)
                throw new ArgumentNullException(nameof(key), "Property is not nullable for class CreateApiKeyResponse.");

            if (prefix.IsSet && prefix.Value == null)
                throw new ArgumentNullException(nameof(prefix), "Property is not nullable for class CreateApiKeyResponse.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class CreateApiKeyResponse.");

            return new CreateApiKeyResponse(id.Value!.Value!, key.Value!, prefix.Value!, message.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CreateApiKeyResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createApiKeyResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateApiKeyResponse createApiKeyResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createApiKeyResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateApiKeyResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createApiKeyResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateApiKeyResponse createApiKeyResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createApiKeyResponse.Key == null)
                throw new ArgumentNullException(nameof(createApiKeyResponse.Key), "Property is required for class CreateApiKeyResponse.");

            if (createApiKeyResponse.Prefix == null)
                throw new ArgumentNullException(nameof(createApiKeyResponse.Prefix), "Property is required for class CreateApiKeyResponse.");

            if (createApiKeyResponse.Message == null)
                throw new ArgumentNullException(nameof(createApiKeyResponse.Message), "Property is required for class CreateApiKeyResponse.");

            writer.WriteString("id", createApiKeyResponse.Id);

            writer.WriteString("key", createApiKeyResponse.Key);

            writer.WriteString("prefix", createApiKeyResponse.Prefix);

            writer.WriteString("message", createApiKeyResponse.Message);
        }
    }
}
