// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HookSniff.Client;

namespace HookSniff.Model
{
    /// <summary>
    /// A DNS record required for domain verification
    /// </summary>
    public partial class DomainDnsRecord : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DomainDnsRecord" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="name">DNS record name/host</param>
        /// <param name="value">DNS record value</param>
        /// <param name="status">status</param>
        [JsonConstructor]
        public DomainDnsRecord(TypeEnum type, string name, string value, StatusEnum status)
        {
            Type = type;
            Name = name;
            Value = value;
            Status = status;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum TXT for value: TXT
            /// </summary>
            TXT = 1,

            /// <summary>
            /// Enum CNAME for value: CNAME
            /// </summary>
            CNAME = 2,

            /// <summary>
            /// Enum A for value: A
            /// </summary>
            A = 3
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("TXT"))
                return TypeEnum.TXT;

            if (value.Equals("CNAME"))
                return TypeEnum.CNAME;

            if (value.Equals("A"))
                return TypeEnum.A;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("TXT"))
                return TypeEnum.TXT;

            if (value.Equals("CNAME"))
                return TypeEnum.CNAME;

            if (value.Equals("A"))
                return TypeEnum.A;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.TXT)
                return "TXT";

            if (value == TypeEnum.CNAME)
                return "CNAME";

            if (value == TypeEnum.A)
                return "A";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 1,

            /// <summary>
            /// Enum Verified for value: verified
            /// </summary>
            Verified = 2,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("verified"))
                return StatusEnum.Verified;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("verified"))
                return StatusEnum.Verified;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Pending)
                return "pending";

            if (value == StatusEnum.Verified)
                return "verified";

            if (value == StatusEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// DNS record name/host
        /// </summary>
        /// <value>DNS record name/host</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// DNS record value
        /// </summary>
        /// <value>DNS record value</value>
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DomainDnsRecord {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DomainDnsRecord" />
    /// </summary>
    public class DomainDnsRecordJsonConverter : JsonConverter<DomainDnsRecord>
    {
        /// <summary>
        /// Deserializes json to <see cref="DomainDnsRecord" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DomainDnsRecord Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DomainDnsRecord.TypeEnum?> type = default;
            Option<string?> name = default;
            Option<string?> value = default;
            Option<DomainDnsRecord.StatusEnum?> status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<DomainDnsRecord.TypeEnum?>(DomainDnsRecord.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<DomainDnsRecord.StatusEnum?>(DomainDnsRecord.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class DomainDnsRecord.", nameof(type));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class DomainDnsRecord.", nameof(name));

            if (!value.IsSet)
                throw new ArgumentException("Property is required for class DomainDnsRecord.", nameof(value));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class DomainDnsRecord.", nameof(status));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class DomainDnsRecord.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class DomainDnsRecord.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class DomainDnsRecord.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class DomainDnsRecord.");

            return new DomainDnsRecord(type.Value!.Value!, name.Value!, value.Value!, status.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="DomainDnsRecord" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="domainDnsRecord"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DomainDnsRecord domainDnsRecord, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, domainDnsRecord, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DomainDnsRecord" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="domainDnsRecord"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DomainDnsRecord domainDnsRecord, JsonSerializerOptions jsonSerializerOptions)
        {
            if (domainDnsRecord.Name == null)
                throw new ArgumentNullException(nameof(domainDnsRecord.Name), "Property is required for class DomainDnsRecord.");

            if (domainDnsRecord.Value == null)
                throw new ArgumentNullException(nameof(domainDnsRecord.Value), "Property is required for class DomainDnsRecord.");

            var typeRawValue = DomainDnsRecord.TypeEnumToJsonValue(domainDnsRecord.Type);
            writer.WriteString("type", typeRawValue);
            writer.WriteString("name", domainDnsRecord.Name);

            writer.WriteString("value", domainDnsRecord.Value);

            var statusRawValue = DomainDnsRecord.StatusEnumToJsonValue(domainDnsRecord.Status);
            writer.WriteString("status", statusRawValue);
        }
    }
}
