// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HookSniff.Client;

namespace HookSniff.Model
{
    /// <summary>
    /// InboundConfig
    /// </summary>
    public partial class InboundConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InboundConfig" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="customerId">customerId</param>
        /// <param name="provider">Provider name (stripe, github, shopify, generic)</param>
        /// <param name="secret">Webhook signing secret</param>
        /// <param name="endpointId">endpointId</param>
        /// <param name="enabled">enabled</param>
        /// <param name="createdAt">createdAt</param>
        [JsonConstructor]
        public InboundConfig(Option<Guid?> id = default, Option<Guid?> customerId = default, Option<string?> provider = default, Option<string?> secret = default, Option<Guid?> endpointId = default, Option<bool?> enabled = default, Option<DateTime?> createdAt = default)
        {
            IdOption = id;
            CustomerIdOption = customerId;
            ProviderOption = provider;
            SecretOption = secret;
            EndpointIdOption = endpointId;
            EnabledOption = enabled;
            CreatedAtOption = createdAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption.Value; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> CustomerIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [JsonPropertyName("customer_id")]
        public Guid? CustomerId { get { return this.CustomerIdOption.Value; } set { this.CustomerIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Provider
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProviderOption { get; private set; }

        /// <summary>
        /// Provider name (stripe, github, shopify, generic)
        /// </summary>
        /// <value>Provider name (stripe, github, shopify, generic)</value>
        [JsonPropertyName("provider")]
        public string? Provider { get { return this.ProviderOption.Value; } set { this.ProviderOption = new(value); } }

        /// <summary>
        /// Used to track the state of Secret
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SecretOption { get; private set; }

        /// <summary>
        /// Webhook signing secret
        /// </summary>
        /// <value>Webhook signing secret</value>
        [JsonPropertyName("secret")]
        public string? Secret { get { return this.SecretOption.Value; } set { this.SecretOption = new(value); } }

        /// <summary>
        /// Used to track the state of EndpointId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> EndpointIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets EndpointId
        /// </summary>
        [JsonPropertyName("endpoint_id")]
        public Guid? EndpointId { get { return this.EndpointIdOption.Value; } set { this.EndpointIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool? Enabled { get { return this.EnabledOption.Value; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime? CreatedAt { get { return this.CreatedAtOption.Value; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InboundConfig {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  Provider: ").Append(Provider).Append("\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("  EndpointId: ").Append(EndpointId).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InboundConfig" />
    /// </summary>
    public class InboundConfigJsonConverter : JsonConverter<InboundConfig>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="InboundConfig" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InboundConfig Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> customerId = default;
            Option<string?> provider = default;
            Option<string?> secret = default;
            Option<Guid?> endpointId = default;
            Option<bool?> enabled = default;
            Option<DateTime?> createdAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "customer_id":
                            customerId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "provider":
                            provider = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "secret":
                            secret = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "endpoint_id":
                            endpointId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "enabled":
                            enabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class InboundConfig.");

            if (customerId.IsSet && customerId.Value == null)
                throw new ArgumentNullException(nameof(customerId), "Property is not nullable for class InboundConfig.");

            if (provider.IsSet && provider.Value == null)
                throw new ArgumentNullException(nameof(provider), "Property is not nullable for class InboundConfig.");

            if (secret.IsSet && secret.Value == null)
                throw new ArgumentNullException(nameof(secret), "Property is not nullable for class InboundConfig.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class InboundConfig.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class InboundConfig.");

            return new InboundConfig(id, customerId, provider, secret, endpointId, enabled, createdAt);
        }

        /// <summary>
        /// Serializes a <see cref="InboundConfig" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="inboundConfig"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InboundConfig inboundConfig, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, inboundConfig, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InboundConfig" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="inboundConfig"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InboundConfig inboundConfig, JsonSerializerOptions jsonSerializerOptions)
        {
            if (inboundConfig.ProviderOption.IsSet && inboundConfig.Provider == null)
                throw new ArgumentNullException(nameof(inboundConfig.Provider), "Property is required for class InboundConfig.");

            if (inboundConfig.SecretOption.IsSet && inboundConfig.Secret == null)
                throw new ArgumentNullException(nameof(inboundConfig.Secret), "Property is required for class InboundConfig.");

            if (inboundConfig.IdOption.IsSet)
                writer.WriteString("id", inboundConfig.IdOption.Value!.Value);

            if (inboundConfig.CustomerIdOption.IsSet)
                writer.WriteString("customer_id", inboundConfig.CustomerIdOption.Value!.Value);

            if (inboundConfig.ProviderOption.IsSet)
                writer.WriteString("provider", inboundConfig.Provider);

            if (inboundConfig.SecretOption.IsSet)
                writer.WriteString("secret", inboundConfig.Secret);

            if (inboundConfig.EndpointIdOption.IsSet)
                if (inboundConfig.EndpointIdOption.Value != null)
                    writer.WriteString("endpoint_id", inboundConfig.EndpointIdOption.Value!.Value);
                else
                    writer.WriteNull("endpoint_id");

            if (inboundConfig.EnabledOption.IsSet)
                writer.WriteBoolean("enabled", inboundConfig.EnabledOption.Value!.Value);

            if (inboundConfig.CreatedAtOption.IsSet)
                writer.WriteString("created_at", inboundConfig.CreatedAtOption.Value!.Value.ToString(CreatedAtFormat));
        }
    }
}
