// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HookSniff.Client;

namespace HookSniff.Model
{
    /// <summary>
    /// Result of processing an inbound webhook
    /// </summary>
    public partial class InboundWebhookResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InboundWebhookResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="status">Processing status of the inbound webhook</param>
        /// <param name="endpointId">endpointId</param>
        /// <param name="receivedAt">receivedAt</param>
        [JsonConstructor]
        public InboundWebhookResponse(Guid id, StatusEnum status, Guid endpointId, DateTime receivedAt)
        {
            Id = id;
            Status = status;
            EndpointId = endpointId;
            ReceivedAt = receivedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Processing status of the inbound webhook
        /// </summary>
        /// <value>Processing status of the inbound webhook</value>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Accepted for value: accepted
            /// </summary>
            Accepted = 1,

            /// <summary>
            /// Enum Rejected for value: rejected
            /// </summary>
            Rejected = 2,

            /// <summary>
            /// Enum Processing for value: processing
            /// </summary>
            Processing = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("accepted"))
                return StatusEnum.Accepted;

            if (value.Equals("rejected"))
                return StatusEnum.Rejected;

            if (value.Equals("processing"))
                return StatusEnum.Processing;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("accepted"))
                return StatusEnum.Accepted;

            if (value.Equals("rejected"))
                return StatusEnum.Rejected;

            if (value.Equals("processing"))
                return StatusEnum.Processing;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum value)
        {
            if (value == StatusEnum.Accepted)
                return "accepted";

            if (value == StatusEnum.Rejected)
                return "rejected";

            if (value == StatusEnum.Processing)
                return "processing";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Processing status of the inbound webhook
        /// </summary>
        /// <value>Processing status of the inbound webhook</value>
        [JsonPropertyName("status")]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets EndpointId
        /// </summary>
        [JsonPropertyName("endpoint_id")]
        public Guid EndpointId { get; set; }

        /// <summary>
        /// Gets or Sets ReceivedAt
        /// </summary>
        [JsonPropertyName("received_at")]
        public DateTime ReceivedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InboundWebhookResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  EndpointId: ").Append(EndpointId).Append("\n");
            sb.Append("  ReceivedAt: ").Append(ReceivedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InboundWebhookResponse" />
    /// </summary>
    public class InboundWebhookResponseJsonConverter : JsonConverter<InboundWebhookResponse>
    {
        /// <summary>
        /// The format to use to serialize ReceivedAt
        /// </summary>
        public static string ReceivedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="InboundWebhookResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InboundWebhookResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<InboundWebhookResponse.StatusEnum?> status = default;
            Option<Guid?> endpointId = default;
            Option<DateTime?> receivedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<InboundWebhookResponse.StatusEnum?>(InboundWebhookResponse.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "endpoint_id":
                            endpointId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "received_at":
                            receivedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class InboundWebhookResponse.", nameof(id));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class InboundWebhookResponse.", nameof(status));

            if (!endpointId.IsSet)
                throw new ArgumentException("Property is required for class InboundWebhookResponse.", nameof(endpointId));

            if (!receivedAt.IsSet)
                throw new ArgumentException("Property is required for class InboundWebhookResponse.", nameof(receivedAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class InboundWebhookResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class InboundWebhookResponse.");

            if (endpointId.IsSet && endpointId.Value == null)
                throw new ArgumentNullException(nameof(endpointId), "Property is not nullable for class InboundWebhookResponse.");

            if (receivedAt.IsSet && receivedAt.Value == null)
                throw new ArgumentNullException(nameof(receivedAt), "Property is not nullable for class InboundWebhookResponse.");

            return new InboundWebhookResponse(id.Value!.Value!, status.Value!.Value!, endpointId.Value!.Value!, receivedAt.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="InboundWebhookResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="inboundWebhookResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InboundWebhookResponse inboundWebhookResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, inboundWebhookResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InboundWebhookResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="inboundWebhookResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InboundWebhookResponse inboundWebhookResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("id", inboundWebhookResponse.Id);

            var statusRawValue = InboundWebhookResponse.StatusEnumToJsonValue(inboundWebhookResponse.Status);
            writer.WriteString("status", statusRawValue);
            writer.WriteString("endpoint_id", inboundWebhookResponse.EndpointId);

            writer.WriteString("received_at", inboundWebhookResponse.ReceivedAt.ToString(ReceivedAtFormat));
        }
    }
}
