// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HookSniff.Client;

namespace HookSniff.Model
{
    /// <summary>
    /// InboundConfigsIdPutRequest
    /// </summary>
    public partial class InboundConfigsIdPutRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InboundConfigsIdPutRequest" /> class.
        /// </summary>
        /// <param name="secret">secret</param>
        /// <param name="endpointId">endpointId</param>
        /// <param name="enabled">enabled</param>
        [JsonConstructor]
        public InboundConfigsIdPutRequest(Option<string?> secret = default, Option<Guid?> endpointId = default, Option<bool?> enabled = default)
        {
            SecretOption = secret;
            EndpointIdOption = endpointId;
            EnabledOption = enabled;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Secret
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SecretOption { get; private set; }

        /// <summary>
        /// Gets or Sets Secret
        /// </summary>
        [JsonPropertyName("secret")]
        public string? Secret { get { return this.SecretOption.Value; } set { this.SecretOption = new(value); } }

        /// <summary>
        /// Used to track the state of EndpointId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> EndpointIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets EndpointId
        /// </summary>
        [JsonPropertyName("endpoint_id")]
        public Guid? EndpointId { get { return this.EndpointIdOption.Value; } set { this.EndpointIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool? Enabled { get { return this.EnabledOption.Value; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InboundConfigsIdPutRequest {\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("  EndpointId: ").Append(EndpointId).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="InboundConfigsIdPutRequest" />
    /// </summary>
    public class InboundConfigsIdPutRequestJsonConverter : JsonConverter<InboundConfigsIdPutRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="InboundConfigsIdPutRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override InboundConfigsIdPutRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> secret = default;
            Option<Guid?> endpointId = default;
            Option<bool?> enabled = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "secret":
                            secret = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "endpoint_id":
                            endpointId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "enabled":
                            enabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (secret.IsSet && secret.Value == null)
                throw new ArgumentNullException(nameof(secret), "Property is not nullable for class InboundConfigsIdPutRequest.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class InboundConfigsIdPutRequest.");

            return new InboundConfigsIdPutRequest(secret, endpointId, enabled);
        }

        /// <summary>
        /// Serializes a <see cref="InboundConfigsIdPutRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="inboundConfigsIdPutRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, InboundConfigsIdPutRequest inboundConfigsIdPutRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, inboundConfigsIdPutRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="InboundConfigsIdPutRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="inboundConfigsIdPutRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, InboundConfigsIdPutRequest inboundConfigsIdPutRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (inboundConfigsIdPutRequest.SecretOption.IsSet && inboundConfigsIdPutRequest.Secret == null)
                throw new ArgumentNullException(nameof(inboundConfigsIdPutRequest.Secret), "Property is required for class InboundConfigsIdPutRequest.");

            if (inboundConfigsIdPutRequest.SecretOption.IsSet)
                writer.WriteString("secret", inboundConfigsIdPutRequest.Secret);

            if (inboundConfigsIdPutRequest.EndpointIdOption.IsSet)
                if (inboundConfigsIdPutRequest.EndpointIdOption.Value != null)
                    writer.WriteString("endpoint_id", inboundConfigsIdPutRequest.EndpointIdOption.Value!.Value);
                else
                    writer.WriteNull("endpoint_id");

            if (inboundConfigsIdPutRequest.EnabledOption.IsSet)
                writer.WriteBoolean("enabled", inboundConfigsIdPutRequest.EnabledOption.Value!.Value);
        }
    }
}
