// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HookSniff.Client;

namespace HookSniff.Model
{
    /// <summary>
    /// PaginatedUsers
    /// </summary>
    public partial class PaginatedUsers : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaginatedUsers" /> class.
        /// </summary>
        /// <param name="users">users</param>
        /// <param name="total">total</param>
        /// <param name="page">page</param>
        /// <param name="perPage">perPage</param>
        [JsonConstructor]
        public PaginatedUsers(List<UserSummary> users, int total, int page, int perPage)
        {
            Users = users;
            Total = total;
            Page = page;
            PerPage = perPage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Users
        /// </summary>
        [JsonPropertyName("users")]
        public List<UserSummary> Users { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonPropertyName("total")]
        public int Total { get; set; }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [JsonPropertyName("page")]
        public int Page { get; set; }

        /// <summary>
        /// Gets or Sets PerPage
        /// </summary>
        [JsonPropertyName("per_page")]
        public int PerPage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaginatedUsers {\n");
            sb.Append("  Users: ").Append(Users).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  PerPage: ").Append(PerPage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PaginatedUsers" />
    /// </summary>
    public class PaginatedUsersJsonConverter : JsonConverter<PaginatedUsers>
    {
        /// <summary>
        /// Deserializes json to <see cref="PaginatedUsers" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PaginatedUsers Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<UserSummary>?> users = default;
            Option<int?> total = default;
            Option<int?> page = default;
            Option<int?> perPage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "users":
                            users = new Option<List<UserSummary>?>(JsonSerializer.Deserialize<List<UserSummary>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "total":
                            total = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "page":
                            page = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "per_page":
                            perPage = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!users.IsSet)
                throw new ArgumentException("Property is required for class PaginatedUsers.", nameof(users));

            if (!total.IsSet)
                throw new ArgumentException("Property is required for class PaginatedUsers.", nameof(total));

            if (!page.IsSet)
                throw new ArgumentException("Property is required for class PaginatedUsers.", nameof(page));

            if (!perPage.IsSet)
                throw new ArgumentException("Property is required for class PaginatedUsers.", nameof(perPage));

            if (users.IsSet && users.Value == null)
                throw new ArgumentNullException(nameof(users), "Property is not nullable for class PaginatedUsers.");

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class PaginatedUsers.");

            if (page.IsSet && page.Value == null)
                throw new ArgumentNullException(nameof(page), "Property is not nullable for class PaginatedUsers.");

            if (perPage.IsSet && perPage.Value == null)
                throw new ArgumentNullException(nameof(perPage), "Property is not nullable for class PaginatedUsers.");

            return new PaginatedUsers(users.Value!, total.Value!.Value!, page.Value!.Value!, perPage.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PaginatedUsers" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paginatedUsers"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PaginatedUsers paginatedUsers, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, paginatedUsers, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PaginatedUsers" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paginatedUsers"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PaginatedUsers paginatedUsers, JsonSerializerOptions jsonSerializerOptions)
        {
            if (paginatedUsers.Users == null)
                throw new ArgumentNullException(nameof(paginatedUsers.Users), "Property is required for class PaginatedUsers.");

            writer.WritePropertyName("users");
            JsonSerializer.Serialize(writer, paginatedUsers.Users, jsonSerializerOptions);
            writer.WriteNumber("total", paginatedUsers.Total);

            writer.WriteNumber("page", paginatedUsers.Page);

            writer.WriteNumber("per_page", paginatedUsers.PerPage);
        }
    }
}
