// <auto-generated>
/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HookSniff.Client;

namespace HookSniff.Model
{
    /// <summary>
    /// UsageResponse
    /// </summary>
    public partial class UsageResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UsageResponse" /> class.
        /// </summary>
        /// <param name="plan">plan</param>
        /// <param name="periodStart">periodStart</param>
        /// <param name="periodEnd">periodEnd</param>
        /// <param name="webhooksUsed">webhooksUsed</param>
        /// <param name="webhooksLimit">webhooksLimit</param>
        /// <param name="endpointsUsed">endpointsUsed</param>
        /// <param name="endpointsLimit">endpointsLimit</param>
        [JsonConstructor]
        public UsageResponse(string plan, DateTime periodStart, DateTime periodEnd, int webhooksUsed, int webhooksLimit, int endpointsUsed, int endpointsLimit)
        {
            Plan = plan;
            PeriodStart = periodStart;
            PeriodEnd = periodEnd;
            WebhooksUsed = webhooksUsed;
            WebhooksLimit = webhooksLimit;
            EndpointsUsed = endpointsUsed;
            EndpointsLimit = endpointsLimit;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Plan
        /// </summary>
        [JsonPropertyName("plan")]
        public string Plan { get; set; }

        /// <summary>
        /// Gets or Sets PeriodStart
        /// </summary>
        [JsonPropertyName("period_start")]
        public DateTime PeriodStart { get; set; }

        /// <summary>
        /// Gets or Sets PeriodEnd
        /// </summary>
        [JsonPropertyName("period_end")]
        public DateTime PeriodEnd { get; set; }

        /// <summary>
        /// Gets or Sets WebhooksUsed
        /// </summary>
        [JsonPropertyName("webhooks_used")]
        public int WebhooksUsed { get; set; }

        /// <summary>
        /// Gets or Sets WebhooksLimit
        /// </summary>
        [JsonPropertyName("webhooks_limit")]
        public int WebhooksLimit { get; set; }

        /// <summary>
        /// Gets or Sets EndpointsUsed
        /// </summary>
        [JsonPropertyName("endpoints_used")]
        public int EndpointsUsed { get; set; }

        /// <summary>
        /// Gets or Sets EndpointsLimit
        /// </summary>
        [JsonPropertyName("endpoints_limit")]
        public int EndpointsLimit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UsageResponse {\n");
            sb.Append("  Plan: ").Append(Plan).Append("\n");
            sb.Append("  PeriodStart: ").Append(PeriodStart).Append("\n");
            sb.Append("  PeriodEnd: ").Append(PeriodEnd).Append("\n");
            sb.Append("  WebhooksUsed: ").Append(WebhooksUsed).Append("\n");
            sb.Append("  WebhooksLimit: ").Append(WebhooksLimit).Append("\n");
            sb.Append("  EndpointsUsed: ").Append(EndpointsUsed).Append("\n");
            sb.Append("  EndpointsLimit: ").Append(EndpointsLimit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UsageResponse" />
    /// </summary>
    public class UsageResponseJsonConverter : JsonConverter<UsageResponse>
    {
        /// <summary>
        /// The format to use to serialize PeriodStart
        /// </summary>
        public static string PeriodStartFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize PeriodEnd
        /// </summary>
        public static string PeriodEndFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="UsageResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UsageResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> plan = default;
            Option<DateTime?> periodStart = default;
            Option<DateTime?> periodEnd = default;
            Option<int?> webhooksUsed = default;
            Option<int?> webhooksLimit = default;
            Option<int?> endpointsUsed = default;
            Option<int?> endpointsLimit = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "plan":
                            plan = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "period_start":
                            periodStart = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "period_end":
                            periodEnd = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "webhooks_used":
                            webhooksUsed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "webhooks_limit":
                            webhooksLimit = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "endpoints_used":
                            endpointsUsed = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "endpoints_limit":
                            endpointsLimit = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!plan.IsSet)
                throw new ArgumentException("Property is required for class UsageResponse.", nameof(plan));

            if (!periodStart.IsSet)
                throw new ArgumentException("Property is required for class UsageResponse.", nameof(periodStart));

            if (!periodEnd.IsSet)
                throw new ArgumentException("Property is required for class UsageResponse.", nameof(periodEnd));

            if (!webhooksUsed.IsSet)
                throw new ArgumentException("Property is required for class UsageResponse.", nameof(webhooksUsed));

            if (!webhooksLimit.IsSet)
                throw new ArgumentException("Property is required for class UsageResponse.", nameof(webhooksLimit));

            if (!endpointsUsed.IsSet)
                throw new ArgumentException("Property is required for class UsageResponse.", nameof(endpointsUsed));

            if (!endpointsLimit.IsSet)
                throw new ArgumentException("Property is required for class UsageResponse.", nameof(endpointsLimit));

            if (plan.IsSet && plan.Value == null)
                throw new ArgumentNullException(nameof(plan), "Property is not nullable for class UsageResponse.");

            if (periodStart.IsSet && periodStart.Value == null)
                throw new ArgumentNullException(nameof(periodStart), "Property is not nullable for class UsageResponse.");

            if (periodEnd.IsSet && periodEnd.Value == null)
                throw new ArgumentNullException(nameof(periodEnd), "Property is not nullable for class UsageResponse.");

            if (webhooksUsed.IsSet && webhooksUsed.Value == null)
                throw new ArgumentNullException(nameof(webhooksUsed), "Property is not nullable for class UsageResponse.");

            if (webhooksLimit.IsSet && webhooksLimit.Value == null)
                throw new ArgumentNullException(nameof(webhooksLimit), "Property is not nullable for class UsageResponse.");

            if (endpointsUsed.IsSet && endpointsUsed.Value == null)
                throw new ArgumentNullException(nameof(endpointsUsed), "Property is not nullable for class UsageResponse.");

            if (endpointsLimit.IsSet && endpointsLimit.Value == null)
                throw new ArgumentNullException(nameof(endpointsLimit), "Property is not nullable for class UsageResponse.");

            return new UsageResponse(plan.Value!, periodStart.Value!.Value!, periodEnd.Value!.Value!, webhooksUsed.Value!.Value!, webhooksLimit.Value!.Value!, endpointsUsed.Value!.Value!, endpointsLimit.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UsageResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="usageResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UsageResponse usageResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, usageResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UsageResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="usageResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UsageResponse usageResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (usageResponse.Plan == null)
                throw new ArgumentNullException(nameof(usageResponse.Plan), "Property is required for class UsageResponse.");

            writer.WriteString("plan", usageResponse.Plan);

            writer.WriteString("period_start", usageResponse.PeriodStart.ToString(PeriodStartFormat));

            writer.WriteString("period_end", usageResponse.PeriodEnd.ToString(PeriodEndFormat));

            writer.WriteNumber("webhooks_used", usageResponse.WebhooksUsed);

            writer.WriteNumber("webhooks_limit", usageResponse.WebhooksLimit);

            writer.WriteNumber("endpoints_used", usageResponse.EndpointsUsed);

            writer.WriteNumber("endpoints_limit", usageResponse.EndpointsLimit);
        }
    }
}
