/*
 * HookSniff API
 *
 * Webhook delivery, monitoring, and management API. All endpoints under `/v1` require authentication via `Authorization: Bearer <api_key>` header unless marked as **Public**. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@hooksniff.vercel.app
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using HookSniff.Api;
using HookSniff.Model;

namespace HookSniff.Client
{
    /// <summary>
    /// Provides hosting configuration for HookSniff
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new AdminAlertRuleJsonConverter());
            _jsonOptions.Converters.Add(new AdminAlertsIdDelete200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new AdminAuditEntryJsonConverter());
            _jsonOptions.Converters.Add(new AdminAuditLogResponseJsonConverter());
            _jsonOptions.Converters.Add(new AdminCreateAlertRequestJsonConverter());
            _jsonOptions.Converters.Add(new AdminFeatureFlagsGet200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new AdminFeatureFlagsIdPutRequestJsonConverter());
            _jsonOptions.Converters.Add(new AdminFeatureFlagsPostRequestJsonConverter());
            _jsonOptions.Converters.Add(new AdminRevenueEntryJsonConverter());
            _jsonOptions.Converters.Add(new AdminRevenueResponseJsonConverter());
            _jsonOptions.Converters.Add(new AdminSdkUpdatePostRequestJsonConverter());
            _jsonOptions.Converters.Add(new AdminSettingsPut200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new AdminSystemStatusJsonConverter());
            _jsonOptions.Converters.Add(new AdminTestWebhookRequestJsonConverter());
            _jsonOptions.Converters.Add(new AdminTestWebhookResponseJsonConverter());
            _jsonOptions.Converters.Add(new AdminUpdateAlertRequestJsonConverter());
            _jsonOptions.Converters.Add(new AdminUserListResponseJsonConverter());
            _jsonOptions.Converters.Add(new AdminUsersIdGet200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new AdminUsersIdGet200ResponseEndpointsInnerJsonConverter());
            _jsonOptions.Converters.Add(new AdminUsersIdGet200ResponseRecentDeliveriesInnerJsonConverter());
            _jsonOptions.Converters.Add(new AdminUsersIdGet200ResponseUsageStatsJsonConverter());
            _jsonOptions.Converters.Add(new AdminUsersIdPlanPutRequestJsonConverter());
            _jsonOptions.Converters.Add(new AdminUsersIdStatusPutRequestJsonConverter());
            _jsonOptions.Converters.Add(new AlertNotificationListResponseJsonConverter());
            _jsonOptions.Converters.Add(new AlertNotificationListResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new AlertRuleJsonConverter());
            _jsonOptions.Converters.Add(new AlertRuleListResponseJsonConverter());
            _jsonOptions.Converters.Add(new AnalyticsTrendPointJsonConverter());
            _jsonOptions.Converters.Add(new AnalyticsTrendResponseJsonConverter());
            _jsonOptions.Converters.Add(new ApiKeyInfoJsonConverter());
            _jsonOptions.Converters.Add(new ApplicationJsonConverter());
            _jsonOptions.Converters.Add(new ApplicationsIdPutRequestJsonConverter());
            _jsonOptions.Converters.Add(new ApplicationsPostRequestJsonConverter());
            _jsonOptions.Converters.Add(new ApplyTemplateRequestJsonConverter());
            _jsonOptions.Converters.Add(new ApplyTemplateResponseJsonConverter());
            _jsonOptions.Converters.Add(new AuditLogEntryJsonConverter());
            _jsonOptions.Converters.Add(new AuditLogListResponseJsonConverter());
            _jsonOptions.Converters.Add(new Auth2faEnablePost200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new Auth2faStatusGet200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new AuthConsentGet200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new AuthConsentPost200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new AuthConsentPostRequestJsonConverter());
            _jsonOptions.Converters.Add(new AuthLoginPost200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new AuthResponseJsonConverter());
            _jsonOptions.Converters.Add(new BatchReplayRequestJsonConverter());
            _jsonOptions.Converters.Add(new BatchResponseJsonConverter());
            _jsonOptions.Converters.Add(new BatchResponseErrorsInnerJsonConverter());
            _jsonOptions.Converters.Add(new BatchWebhookRequestJsonConverter());
            _jsonOptions.Converters.Add(new BatchWebhookResponseJsonConverter());
            _jsonOptions.Converters.Add(new BillingPortalPost200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new BillingPortalResponseJsonConverter());
            _jsonOptions.Converters.Add(new CancelSubscriptionRequestJsonConverter());
            _jsonOptions.Converters.Add(new CancelSubscriptionResponseJsonConverter());
            _jsonOptions.Converters.Add(new ChangePasswordRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChangeRoleRequestJsonConverter());
            _jsonOptions.Converters.Add(new ChurnResponseJsonConverter());
            _jsonOptions.Converters.Add(new ChurnedUserJsonConverter());
            _jsonOptions.Converters.Add(new Confirm2faRequestJsonConverter());
            _jsonOptions.Converters.Add(new ContactRequestJsonConverter());
            _jsonOptions.Converters.Add(new ContactResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateAlertRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateAlertRuleRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateApiKeyResponseJsonConverter());
            _jsonOptions.Converters.Add(new CreateCustomDomainRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateEndpointRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateRoutingRuleRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateSSOConfigRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateTeamRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateTransformRuleRequestJsonConverter());
            _jsonOptions.Converters.Add(new CreateWebhookRequestJsonConverter());
            _jsonOptions.Converters.Add(new CustomDomainJsonConverter());
            _jsonOptions.Converters.Add(new CustomDomainListResponseJsonConverter());
            _jsonOptions.Converters.Add(new CustomDomainsPostRequestJsonConverter());
            _jsonOptions.Converters.Add(new CustomerResponseJsonConverter());
            _jsonOptions.Converters.Add(new DailyDeliveryCountJsonConverter());
            _jsonOptions.Converters.Add(new DeliveryJsonConverter());
            _jsonOptions.Converters.Add(new DeliveryAttemptJsonConverter());
            _jsonOptions.Converters.Add(new DeliveryAttemptListResponseJsonConverter());
            _jsonOptions.Converters.Add(new DeliveryDetailResponseJsonConverter());
            _jsonOptions.Converters.Add(new DeliveryListResponseJsonConverter());
            _jsonOptions.Converters.Add(new DeliveryTrendResponseJsonConverter());
            _jsonOptions.Converters.Add(new DeliveryTrendResponseBucketsInnerJsonConverter());
            _jsonOptions.Converters.Add(new DeployInfoJsonConverter());
            _jsonOptions.Converters.Add(new DeviceListResponseJsonConverter());
            _jsonOptions.Converters.Add(new DeviceTokenResponseJsonConverter());
            _jsonOptions.Converters.Add(new Disable2faRequestJsonConverter());
            _jsonOptions.Converters.Add(new DomainDnsRecordJsonConverter());
            _jsonOptions.Converters.Add(new EmbedConfigJsonConverter());
            _jsonOptions.Converters.Add(new EmbedConfigThemeJsonConverter());
            _jsonOptions.Converters.Add(new Enable2faRequestJsonConverter());
            _jsonOptions.Converters.Add(new Enable2faResponseJsonConverter());
            _jsonOptions.Converters.Add(new EndpointJsonConverter());
            _jsonOptions.Converters.Add(new EndpointHealthJsonConverter());
            _jsonOptions.Converters.Add(new EndpointListResponseJsonConverter());
            _jsonOptions.Converters.Add(new EndpointsEndpointIdTransformsTestPostRequestJsonConverter());
            _jsonOptions.Converters.Add(new EndpointsIdRotateSecretPost200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new ErrorJsonConverter());
            _jsonOptions.Converters.Add(new EventTypeJsonConverter());
            _jsonOptions.Converters.Add(new EventTypeCountJsonConverter());
            _jsonOptions.Converters.Add(new EventTypeListResponseJsonConverter());
            _jsonOptions.Converters.Add(new ExportDataResponseJsonConverter());
            _jsonOptions.Converters.Add(new FeatureFlagJsonConverter());
            _jsonOptions.Converters.Add(new ForgotPasswordRequestJsonConverter());
            _jsonOptions.Converters.Add(new InboundConfigJsonConverter());
            _jsonOptions.Converters.Add(new InboundConfigsIdPutRequestJsonConverter());
            _jsonOptions.Converters.Add(new InboundConfigsPostRequestJsonConverter());
            _jsonOptions.Converters.Add(new InboundWebhookRequestJsonConverter());
            _jsonOptions.Converters.Add(new InboundWebhookResponseJsonConverter());
            _jsonOptions.Converters.Add(new InviteMemberRequestJsonConverter());
            _jsonOptions.Converters.Add(new InviteRequestJsonConverter());
            _jsonOptions.Converters.Add(new InvoiceListResponseJsonConverter());
            _jsonOptions.Converters.Add(new InvoiceResponseJsonConverter());
            _jsonOptions.Converters.Add(new LatencyResponseJsonConverter());
            _jsonOptions.Converters.Add(new LatencyTrendResponseJsonConverter());
            _jsonOptions.Converters.Add(new LatencyTrendResponseBucketsInnerJsonConverter());
            _jsonOptions.Converters.Add(new LoginRequestJsonConverter());
            _jsonOptions.Converters.Add(new LogoutRequestJsonConverter());
            _jsonOptions.Converters.Add(new NotificationJsonConverter());
            _jsonOptions.Converters.Add(new NotificationListResponseJsonConverter());
            _jsonOptions.Converters.Add(new NotificationPreferencesJsonConverter());
            _jsonOptions.Converters.Add(new NotificationsUnreadCountGet200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new OAuthCallbackRequestJsonConverter());
            _jsonOptions.Converters.Add(new OAuthLoginRedirectJsonConverter());
            _jsonOptions.Converters.Add(new OAuthProviderJsonConverter());
            _jsonOptions.Converters.Add(new OAuthProviderListResponseJsonConverter());
            _jsonOptions.Converters.Add(new OutboundIPsResponseJsonConverter());
            _jsonOptions.Converters.Add(new OutboundIpsResponseJsonConverter());
            _jsonOptions.Converters.Add(new PaginatedUsersJsonConverter());
            _jsonOptions.Converters.Add(new PlatformSettingsJsonConverter());
            _jsonOptions.Converters.Add(new PlaygroundGet200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PlaygroundTestRequestJsonConverter());
            _jsonOptions.Converters.Add(new PlaygroundTestResponseJsonConverter());
            _jsonOptions.Converters.Add(new PortalConfigJsonConverter());
            _jsonOptions.Converters.Add(new PortalNotificationsPut200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new PortalProfileJsonConverter());
            _jsonOptions.Converters.Add(new PortalSessionJsonConverter());
            _jsonOptions.Converters.Add(new RateLimitConfigJsonConverter());
            _jsonOptions.Converters.Add(new RateLimitUsageJsonConverter());
            _jsonOptions.Converters.Add(new RefreshTokenRequestJsonConverter());
            _jsonOptions.Converters.Add(new RegisterDeviceRequestJsonConverter());
            _jsonOptions.Converters.Add(new RegisterRequestJsonConverter());
            _jsonOptions.Converters.Add(new RegisterSchemaRequestJsonConverter());
            _jsonOptions.Converters.Add(new ReplayDeliveryResponseJsonConverter());
            _jsonOptions.Converters.Add(new ResendVerificationRequestJsonConverter());
            _jsonOptions.Converters.Add(new ResetPasswordRequestJsonConverter());
            _jsonOptions.Converters.Add(new RetryPolicyJsonConverter());
            _jsonOptions.Converters.Add(new RevenueResponseJsonConverter());
            _jsonOptions.Converters.Add(new RevenueResponseMonthlyRevenueInnerJsonConverter());
            _jsonOptions.Converters.Add(new RevenueResponseRevenueByPlanInnerJsonConverter());
            _jsonOptions.Converters.Add(new RotateSecretResponseJsonConverter());
            _jsonOptions.Converters.Add(new RoutingInfoJsonConverter());
            _jsonOptions.Converters.Add(new RoutingRuleListResponseJsonConverter());
            _jsonOptions.Converters.Add(new RoutingRuleListResponseDataInnerJsonConverter());
            _jsonOptions.Converters.Add(new SSOConfigJsonConverter());
            _jsonOptions.Converters.Add(new SSOConfigListResponseJsonConverter());
            _jsonOptions.Converters.Add(new SchemaListResponseJsonConverter());
            _jsonOptions.Converters.Add(new SchemaResponseJsonConverter());
            _jsonOptions.Converters.Add(new SearchRequestJsonConverter());
            _jsonOptions.Converters.Add(new SearchRequestFiltersJsonConverter());
            _jsonOptions.Converters.Add(new SearchResponseJsonConverter());
            _jsonOptions.Converters.Add(new SearchResultJsonConverter());
            _jsonOptions.Converters.Add(new ServiceTokenJsonConverter());
            _jsonOptions.Converters.Add(new ServiceTokenCreateResponseJsonConverter());
            _jsonOptions.Converters.Add(new ServiceTokensIdPutRequestJsonConverter());
            _jsonOptions.Converters.Add(new ServiceTokensIdRevealPost200ResponseJsonConverter());
            _jsonOptions.Converters.Add(new ServiceTokensPostRequestJsonConverter());
            _jsonOptions.Converters.Add(new SimulatorPostRequestJsonConverter());
            _jsonOptions.Converters.Add(new SimulatorRequestJsonConverter());
            _jsonOptions.Converters.Add(new SimulatorResponseJsonConverter());
            _jsonOptions.Converters.Add(new SsoConfigPostRequestJsonConverter());
            _jsonOptions.Converters.Add(new StatsResponseJsonConverter());
            _jsonOptions.Converters.Add(new StreamParamsJsonConverter());
            _jsonOptions.Converters.Add(new SubscriptionResponseJsonConverter());
            _jsonOptions.Converters.Add(new SuccessRateResponseJsonConverter());
            _jsonOptions.Converters.Add(new SystemStatsJsonConverter());
            _jsonOptions.Converters.Add(new SystemStatsPlanBreakdownInnerJsonConverter());
            _jsonOptions.Converters.Add(new SystemStatusJsonConverter());
            _jsonOptions.Converters.Add(new SystemStatusComponentsInnerJsonConverter());
            _jsonOptions.Converters.Add(new TeamJsonConverter());
            _jsonOptions.Converters.Add(new TeamDetailResponseJsonConverter());
            _jsonOptions.Converters.Add(new TeamInviteJsonConverter());
            _jsonOptions.Converters.Add(new TeamListResponseJsonConverter());
            _jsonOptions.Converters.Add(new TeamMemberJsonConverter());
            _jsonOptions.Converters.Add(new TeamMemberListResponseJsonConverter());
            _jsonOptions.Converters.Add(new TemplateListResponseJsonConverter());
            _jsonOptions.Converters.Add(new TestWebhookRequestJsonConverter());
            _jsonOptions.Converters.Add(new TestWebhookResponseJsonConverter());
            _jsonOptions.Converters.Add(new TransformRuleJsonConverter());
            _jsonOptions.Converters.Add(new TransformRuleListResponseJsonConverter());
            _jsonOptions.Converters.Add(new TwoFactorRequiredResponseJsonConverter());
            _jsonOptions.Converters.Add(new UpdateAlertRuleRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateEndpointRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateNotificationPreferencesJsonConverter());
            _jsonOptions.Converters.Add(new UpdateProfileRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateRoutingRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateRoutingRuleRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateSSOConfigRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateSubscriptionRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateTeamRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateTransformRuleRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpgradeRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpgradeResponseJsonConverter());
            _jsonOptions.Converters.Add(new UsageResponseJsonConverter());
            _jsonOptions.Converters.Add(new UsageStatsResponseJsonConverter());
            _jsonOptions.Converters.Add(new UserAnalyticsJsonConverter());
            _jsonOptions.Converters.Add(new UserSummaryJsonConverter());
            _jsonOptions.Converters.Add(new ValidateEventRequestJsonConverter());
            _jsonOptions.Converters.Add(new ValidateEventResponseJsonConverter());
            _jsonOptions.Converters.Add(new ValidateEventResponseErrorsInnerJsonConverter());
            _jsonOptions.Converters.Add(new Verify2faRequestJsonConverter());
            _jsonOptions.Converters.Add(new VerifyCustomDomainResponseJsonConverter());
            _jsonOptions.Converters.Add(new VerifyEmailRequestJsonConverter());
            _jsonOptions.Converters.Add(new WebhookFilterJsonConverter());
            _jsonOptions.Converters.Add(new WebhookTemplateJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<APIKeysApiEvents>();
            _services.AddSingleton<AdminApiEvents>();
            _services.AddSingleton<AlertsApiEvents>();
            _services.AddSingleton<AnalyticsApiEvents>();
            _services.AddSingleton<ApplicationsApiEvents>();
            _services.AddSingleton<AuditLogApiEvents>();
            _services.AddSingleton<AuthApiEvents>();
            _services.AddSingleton<BillingApiEvents>();
            _services.AddSingleton<ContactApiEvents>();
            _services.AddSingleton<CustomDomainsApiEvents>();
            _services.AddSingleton<CustomerPortalApiEvents>();
            _services.AddSingleton<DeliveryDetailsApiEvents>();
            _services.AddSingleton<DevicesApiEvents>();
            _services.AddSingleton<EmbedApiEvents>();
            _services.AddSingleton<EndpointsApiEvents>();
            _services.AddSingleton<EventsApiEvents>();
            _services.AddSingleton<HealthApiEvents>();
            _services.AddSingleton<InboundApiEvents>();
            _services.AddSingleton<NotificationsApiEvents>();
            _services.AddSingleton<OAuthApiEvents>();
            _services.AddSingleton<OutboundIPsApiEvents>();
            _services.AddSingleton<PlaygroundApiEvents>();
            _services.AddSingleton<RateLimitsApiEvents>();
            _services.AddSingleton<RoutingApiEvents>();
            _services.AddSingleton<SSOApiEvents>();
            _services.AddSingleton<SchemasApiEvents>();
            _services.AddSingleton<SearchApiEvents>();
            _services.AddSingleton<ServiceTokensApiEvents>();
            _services.AddSingleton<SimulatorApiEvents>();
            _services.AddSingleton<StatsApiEvents>();
            _services.AddSingleton<StreamApiEvents>();
            _services.AddSingleton<TeamsApiEvents>();
            _services.AddSingleton<TemplatesApiEvents>();
            _services.AddSingleton<TransformsApiEvents>();
            _services.AddSingleton<WebhooksApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IAPIKeysApi, APIKeysApi>("HookSniff.Api.IAPIKeysApi", client));
            builders.Add(_services.AddHttpClient<IAdminApi, AdminApi>("HookSniff.Api.IAdminApi", client));
            builders.Add(_services.AddHttpClient<IAlertsApi, AlertsApi>("HookSniff.Api.IAlertsApi", client));
            builders.Add(_services.AddHttpClient<IAnalyticsApi, AnalyticsApi>("HookSniff.Api.IAnalyticsApi", client));
            builders.Add(_services.AddHttpClient<IApplicationsApi, ApplicationsApi>("HookSniff.Api.IApplicationsApi", client));
            builders.Add(_services.AddHttpClient<IAuditLogApi, AuditLogApi>("HookSniff.Api.IAuditLogApi", client));
            builders.Add(_services.AddHttpClient<IAuthApi, AuthApi>("HookSniff.Api.IAuthApi", client));
            builders.Add(_services.AddHttpClient<IBillingApi, BillingApi>("HookSniff.Api.IBillingApi", client));
            builders.Add(_services.AddHttpClient<IContactApi, ContactApi>("HookSniff.Api.IContactApi", client));
            builders.Add(_services.AddHttpClient<ICustomDomainsApi, CustomDomainsApi>("HookSniff.Api.ICustomDomainsApi", client));
            builders.Add(_services.AddHttpClient<ICustomerPortalApi, CustomerPortalApi>("HookSniff.Api.ICustomerPortalApi", client));
            builders.Add(_services.AddHttpClient<IDeliveryDetailsApi, DeliveryDetailsApi>("HookSniff.Api.IDeliveryDetailsApi", client));
            builders.Add(_services.AddHttpClient<IDevicesApi, DevicesApi>("HookSniff.Api.IDevicesApi", client));
            builders.Add(_services.AddHttpClient<IEmbedApi, EmbedApi>("HookSniff.Api.IEmbedApi", client));
            builders.Add(_services.AddHttpClient<IEndpointsApi, EndpointsApi>("HookSniff.Api.IEndpointsApi", client));
            builders.Add(_services.AddHttpClient<IEventsApi, EventsApi>("HookSniff.Api.IEventsApi", client));
            builders.Add(_services.AddHttpClient<IHealthApi, HealthApi>("HookSniff.Api.IHealthApi", client));
            builders.Add(_services.AddHttpClient<IInboundApi, InboundApi>("HookSniff.Api.IInboundApi", client));
            builders.Add(_services.AddHttpClient<INotificationsApi, NotificationsApi>("HookSniff.Api.INotificationsApi", client));
            builders.Add(_services.AddHttpClient<IOAuthApi, OAuthApi>("HookSniff.Api.IOAuthApi", client));
            builders.Add(_services.AddHttpClient<IOutboundIPsApi, OutboundIPsApi>("HookSniff.Api.IOutboundIPsApi", client));
            builders.Add(_services.AddHttpClient<IPlaygroundApi, PlaygroundApi>("HookSniff.Api.IPlaygroundApi", client));
            builders.Add(_services.AddHttpClient<IRateLimitsApi, RateLimitsApi>("HookSniff.Api.IRateLimitsApi", client));
            builders.Add(_services.AddHttpClient<IRoutingApi, RoutingApi>("HookSniff.Api.IRoutingApi", client));
            builders.Add(_services.AddHttpClient<ISSOApi, SSOApi>("HookSniff.Api.ISSOApi", client));
            builders.Add(_services.AddHttpClient<ISchemasApi, SchemasApi>("HookSniff.Api.ISchemasApi", client));
            builders.Add(_services.AddHttpClient<ISearchApi, SearchApi>("HookSniff.Api.ISearchApi", client));
            builders.Add(_services.AddHttpClient<IServiceTokensApi, ServiceTokensApi>("HookSniff.Api.IServiceTokensApi", client));
            builders.Add(_services.AddHttpClient<ISimulatorApi, SimulatorApi>("HookSniff.Api.ISimulatorApi", client));
            builders.Add(_services.AddHttpClient<IStatsApi, StatsApi>("HookSniff.Api.IStatsApi", client));
            builders.Add(_services.AddHttpClient<IStreamApi, StreamApi>("HookSniff.Api.IStreamApi", client));
            builders.Add(_services.AddHttpClient<ITeamsApi, TeamsApi>("HookSniff.Api.ITeamsApi", client));
            builders.Add(_services.AddHttpClient<ITemplatesApi, TemplatesApi>("HookSniff.Api.ITemplatesApi", client));
            builders.Add(_services.AddHttpClient<ITransformsApi, TransformsApi>("HookSniff.Api.ITransformsApi", client));
            builders.Add(_services.AddHttpClient<IWebhooksApi, WebhooksApi>("HookSniff.Api.IWebhooksApi", client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
